algoritmo "dados"
var
nome, telefone : caractere
idade : inteiro
peso, altura : real

inicio
escreva("Informe o nome completo: ")
leia(nome)

escreva("Informe a idade: ")
leia(idade)

escreva("Informe o peso: ")
leia(peso)

escreva("Informe a altura: ")
leia(altura)

escreva("Informe o telefone: ")
leia(telefone)

escreval("O nome é: ", nome)
escreval("A idade é: ", idade)
escreval("O peso é: ", peso)
escreval("A altura é: ", altura)
escreval("O telefone é: ", telefone)

fimalgoritmo
