algoritmo "área_triângulo"
var
base, h, a : real

inicio

//Título
escreval("  ---------------------------------  ")
escreval("   CALCULE A ÁREA DE UM TRIÂNGULO")
escreval("  ---------------------------------  ")
// base e altura
escreval("Informe a base do triângulo: ")
leia(base)
escreva("Informe a altura do triângulo: ")
leia(h)
//área
 a <- (base*h)/2
 // resposta
escreva("O triângulo informado tem uma área de: ", a)


fimalgoritmo
